/** 
 * Project Name:o2p-serviceAgent-core 
 * File Name:ProtocolValidateTest.java 
 * Package Name:com.asiainfo.eaap.o2p.validate 
 * Date:2015年2月12日上午10:17:31 
 * Copyright (c) 2015, www.asiainfo.com All Rights Reserved. 
 * 
*/  
  
package com.asiainfo.eaap.o2p.validate;  

import java.io.UnsupportedEncodingException;

import com.ailk.eaap.op2.serviceagent.validate.service.ProtocolValidateServ;

/** 
 * ClassName:ProtocolValidateTest  
 * Function: TODO ADD FUNCTION.  
 * Reason:   TODO ADD REASON.  
 * Date:     2015年2月12日 上午10:17:31  
 * @author   wuwz 
 * @version   
 * @since    JDK 1.6 
 *    
 */
public class ProtocolValidateTest {

	public static void main(String[] args) throws UnsupportedEncodingException {
		 ProtocolValidateServ pt = new ProtocolValidateServ();
		 String reqXml = "<ContractRoot>                                                                                                                                                                                                                                                                                                                                                              "+
"<RequestHead>                                                                                                                                                                                                                                                                                                                                                               "+
"	<TransactionID>6001010005201406201931232917</TransactionID>                                                                                                                                                                                                                                                                                                                "+
"	<Sign>7afde0febabf47c289352d7fc7d416cd</Sign>                                                                                                                                                                                                                                                                                                                              "+
"	<AppKey>6001010005</AppKey>                                                                                                                                                                                                                                                                                                                                                "+
"	<Method>Traffic.tackpackageApply</Method>                                                                                                                                                                                                                                                                                                                                  "+
"	<Version>1.0</Version>                                                                                                                                                                                                                                                                                                                                                     "+
"	<ReqTime>20150101102102</ReqTime>                                                                                                                                                                                                                                                                                                                                          "+
"</RequestHead>                                                                                                                                                                                                                                                                                                                                                              "+
"<RequestBody>                                                                                                                                                                                                                                                                                                                                                               "+
"	<AreaCode>020</AreaCode>                                                                                                                                                                                                                                                                                                                                                   "+
"	<AccNBR>18028687420</AccNBR>                                                                                                                                                                                                                                                                                                                                               "+
"	<BizType>CDMA</BizType>                                                                                                                                                                                                                                                                                                                                                    "+
"	<CustCode>2020250366480000</CustCode>                                                                                                                                                                                                                                                                                                                                      "+
"	<CustID>2962591861</CustID>                                                                                                                                                                                                                                                                                                                                                "+
"	<CustName>TName_2962591861</CustName>                                                                                                                                                                                                                                                                                                                                      "+
"	<CustNature>02</CustNature>                                                                                                                                                                                                                                                                                                                                                "+
"    <CustType>03</CustType>                                                                                                                                                                                                                                                                                                                                                 "+
"	<IndustryBigType>50</IndustryBigType>                                                                                                                                                                                                                                                                                                                                      "+
"	<IndustrySmallType>500101</IndustrySmallType>                                                                                                                                                                                                                                                                                                                              "+
"	<CardType>01</CardType>                                                                                                                                                                                                                                                                                                                                                    "+
"	<CardID>440182198911291530</CardID>                                                                                                                                                                                                                                                                                                                                        "+
"	<CustContact>Linkman_2630385091</CustContact>                                                                                                                                                                                                                                                                                                                              "+
"	<CustTelphone>18912345678</CustTelphone>                                                                                                                                                                                                                                                                                                                                   "+
"	<CustAddr>Detail_2630385091</CustAddr>                                                                                                                                                                                                                                                                                                                                     "+
"	<PostCode></PostCode>                                                                                                                                                                                                                                                                                                                                                      "+
"	<Email></Email>                                                                                                                                                                                                                                                                                                                                                            "+
"	<FaxNumber></FaxNumber>                                                                                                                                                                                                                                                                                                                                                    "+
"	<ContractID></ContractID>                                                                                                                                                                                                                                                                                                                                                  "+
"	<ServiceCode>GZ200000003662052539</ServiceCode>                                                                                                                                                                                                                                                                                                                            "+
"	<ServiceID>3662052539</ServiceID>                                                                                                                                                                                                                                                                                                                                          "+
"	<ProductID>3205</ProductID>                                                                                                                                                                                                                                                                                                                                                "+
"	<HandleAccNBR>18028687420</HandleAccNBR>                                                                                                                                                                                                                                                                                                                                   "+
"	<HandleAccType>1</HandleAccType>                                                                                                                                                                                                                                                                                                                                           "+
"	<DealType>0</DealType>                                                                                                                                                                                                                                                                                                                                                     "+
"	<HandleFlag>0</HandleFlag>                                                                                                                                                                                                                                                                                                                                                 "+
"	<OrderState></OrderState>                                                                                                                                                                                                                                                                                                                                                  "+
"	<ModifyUserID></ModifyUserID>                                                                                                                                                                                                                                                                                                                                              "+
"	<AuditContent></AuditContent>                                                                                                                                                                                                                                                                                                                                              "+
"	<DealContent></DealContent>                                                                                                                                                                                                                                                                                                                                                "+
"	<FeedBack></FeedBack>                                                                                                                                                                                                                                                                                                                                                      "+
"	<FailNews></FailNews>                                                                                                                                                                                                                                                                                                                                                      "+
"	<ReplyEmail></ReplyEmail>                                                                                                                                                                                                                                                                                                                                                  "+
"	<ReplyPhsNumber></ReplyPhsNumber>                                                                                                                                                                                                                                                                                                                                          "+
"	<LinkPeople></LinkPeople>                                                                                                                                                                                                                                                                                                                                                  "+
"	<LinkPhone></LinkPhone>                                                                                                                                                                                                                                                                                                                                                    "+
"	<RecommendPeople></RecommendPeople>                                                                                                                                                                                                                                                                                                                                        "+
"	<BrandBigType></BrandBigType>                                                                                                                                                                                                                                                                                                                                              "+
"	<BrandSmallType></BrandSmallType>                                                                                                                                                                                                                                                                                                                                          "+
"	<OrderSource>2</OrderSource>                                                                                                                                                                                                                                                                                                                                               "+
"	<OrderType></OrderType>                                                                                                                                                                                                                                                                                                                                                    "+
"	<UserIP></UserIP>                                                                                                                                                                                                                                                                                                                                                          "+
"	<GlobalOrderNbr></GlobalOrderNbr>                                                                                                                                                                                                                                                                                                                                          "+
"	<WebOrderID></WebOrderID>                                                                                                                                                                                                                                                                                                                                                  "+
"	<Url></Url>                                                                                                                                                                                                                                                                                                                                                                "+
"	<DeriveFlag>3</DeriveFlag>                                                                                                                                                                                                                                                                                                                                                 "+
"	                                                                                                                                                                                                                                                                                                                                                                           "+
"<DetailOrderInfo>                                                                                                                                                                                                                                                                                                                                                           "+
"	<AttrID>30197839</AttrID>                                                                                                                                                                                                                                                                                                                                                  "+
"	<ProName>hint_cannotOper</ProName>                                                                                                                                                                                                                                                                                                                                         "+
"	<AttrName>不符合办理条件下单失败</AttrName>                                                                                                                                                                                                                                                                                                                                "+
"    <AttrValue>尊敬的{USER_NAME}用户，您当前不满足申请条件，暂不能申请{currentComboDesc}手机上网加餐包。感谢您的使用</AttrValue>                                                                                                                                                                                                                                            "+
"	<AttrValueName></AttrValueName>                                                                                                                                                                                                                                                                                                                                            "+
"	<DispSeq>0</DispSeq>                                                                                                                                                                                                                                                                                                                                                       "+
"</DetailOrderInfo>                                                                                                                                                                                                                                                                                                                                                          "+
"                                                                                                                                                                                                                                                                                                                                                                            "+
"<DetailOrderInfo>                                                                                                                                                                                                                                                                                                                                                           "+
"	<AttrID>30197844</AttrID>                                                                                                                                                                                                                                                                                                                                                  "+
"	<ProName>hint_exception</ProName>                                                                                                                                                                                                                                                                                                                                          "+
"	<AttrName>程序类异常</AttrName>                                                                                                                                                                                                                                                                                                                                            "+
"    <AttrValue>尊敬的{USER_NAME}用户，非常抱歉，您的业务办理失败，请稍后再试。感谢您的使用。</AttrValue>                                                                                                                                                                                                                                                                    "+
"	<AttrValueName></AttrValueName>                                                                                                                                                                                                                                                                                                                                            "+
"	<DispSeq>0</DispSeq>                                                                                                                                                                                                                                                                                                                                                       "+
"</DetailOrderInfo>                                                                                                                                                                                                                                                                                                                                                          "+
"                                                                                                                                                                                                                                                                                                                                                                            "+
"<DetailOrderInfo>                                                                                                                                                                                                                                                                                                                                                           "+
"	<AttrID>30197840</AttrID>                                                                                                                                                                                                                                                                                                                                                  "+
"	<ProName>hint_first</ProName>                                                                                                                                                                                                                                                                                                                                              "+
"	<AttrName>首次办理</AttrName>                                                                                                                                                                                                                                                                                                                                              "+
"    <AttrValue>尊敬的{USER_NAME}用户：您已成功开通{currentComboDesc}手机上网加餐包，订单编号：{orderNo}，自{dateNow}生效，仅限当月有效。本套餐含国内（不含港澳台）CTWAP/CTNET30M流量，超出部分按0.0003元/KB计费，月最高消费为1000元，流量20G封顶。感谢您的使用。</AttrValue>                                                                                                "+
"	<AttrValueName></AttrValueName>                                                                                                                                                                                                                                                                                                                                            "+
"	<DispSeq>0</DispSeq>                                                                                                                                                                                                                                                                                                                                                       "+
"</DetailOrderInfo>                                                                                                                                                                                                                                                                                                                                                          "+
"                                                                                                                                                                                                                                                                                                                                                                            "+
"<DetailOrderInfo>                                                                                                                                                                                                                                                                                                                                                           "+
"	<AttrID>30197843</AttrID>                                                                                                                                                                                                                                                                                                                                                  "+
"	<ProName>hint_Nofirst</ProName>                                                                                                                                                                                                                                                                                                                                            "+
"	<AttrName>非首次办理</AttrName>                                                                                                                                                                                                                                                                                                                                            "+
"    <AttrValue>尊敬的{USER_NAME}用户：您已成功开通{currentComboDesc}手机上网加餐包，订单编号：{orderNo}，自{dateNow}生效，本月开通的加餐包有：{operedCombo}，共开通{amount}个加餐包。仅限当月有效。本套餐含国内（不含港澳台）CTWAP/CTNET30M流量，超出部分按0.0003元/KB计费，月最高消费为1000元，流量20G封顶。感谢您的使用。</AttrValue>                                     "+
"	<AttrValueName></AttrValueName>                                                                                                                                                                                                                                                                                                                                            "+
"	<DispSeq>0</DispSeq>                                                                                                                                                                                                                                                                                                                                                       "+
"</DetailOrderInfo>                                                                                                                                                                                                                                                                                                                                                          "+
"                                                                                                                                                                                                                                                                                                                                                                            "+
"<DetailOrderInfo>                                                                                                                                                                                                                                                                                                                                                           "+
"	<AttrID>30197841</AttrID>                                                                                                                                                                                                                                                                                                                                                  "+
"	<ProName>payType</ProName>                                                                                                                                                                                                                                                                                                                                                 "+
"	<AttrName>付费类型</AttrName>                                                                                                                                                                                                                                                                                                                                              "+
"    <AttrValue>001</AttrValue>                                                                                                                                                                                                                                                                                                                                              "+
"	<AttrValueName>001</AttrValueName>                                                                                                                                                                                                                                                                                                                                         "+
"	<DispSeq>0</DispSeq>                                                                                                                                                                                                                                                                                                                                                       "+
"</DetailOrderInfo>                                                                                                                                                                                                                                                                                                                                                          "+
"                                                                                                                                                                                                                                                                                                                                                                            "+
"                                                                                                                                                                                                                                                                                                                                                                            "+
"<DetailOrderInfo>                                                                                                                                                                                                                                                                                                                                                           "+
"	<AttrID>30197836</AttrID>                                                                                                                                                                                                                                                                                                                                                  "+
"	<ProName>operedCombo</ProName>                                                                                                                                                                                                                                                                                                                                             "+
"	<AttrName>已经办理加餐包描述</AttrName>                                                                                                                                                                                                                                                                                                                                    "+
"    <AttrValue>20元包150M、20元包150M、20元包150M、</AttrValue>                                                                                                                                                                                                                                                                                                             "+
"	<AttrValueName>20元包150M、20元包150M、20元包150M、</AttrValueName>                                                                                                                                                                                                                                                                                                        "+
"	<DispSeq>0</DispSeq>                                                                                                                                                                                                                                                                                                                                                       "+
"</DetailOrderInfo>                                                                                                                                                                                                                                                                                                                                                          "+
"                                                                                                                                                                                                                                                                                                                                                                            "+
"                                                                                                                                                                                                                                                                                                                                                                            "+
"<DetailOrderInfo>                                                                                                                                                                                                                                                                                                                                                           "+
"	<AttrID>30197845</AttrID>                                                                                                                                                                                                                                                                                                                                                  "+
"	<ProName>hint_hasOpered</ProName>                                                                                                                                                                                                                                                                                                                                          "+
"	<AttrName>已经办理提示</AttrName>                                                                                                                                                                                                                                                                                                                                          "+
"    <AttrValue>尊敬的{USER_NAME}用户，您当月已经办理{currentComboDesc}手机上网加餐包套餐，不能重复办理。请选择其他档次加餐包套餐。感谢您使用</AttrValue>                                                                                                                                                                                                                    "+
"	<AttrValueName></AttrValueName>                                                                                                                                                                                                                                                                                                                                            "+
"	<DispSeq>0</DispSeq>                                                                                                                                                                                                                                                                                                                                                       "+
"</DetailOrderInfo>                                                                                                                                                                                                                                                                                                                                                          "+
"                                                                                                                                                                                                                                                                                                                                                                            "+
"                                                                                                                                                                                                                                                                                                                                                                            "+
"<DetailOrderInfo>                                                                                                                                                                                                                                                                                                                                                           "+
"	<AttrID>30197842</AttrID>                                                                                                                                                                                                                                                                                                                                                  "+
"	<ProName>flowCombo</ProName>                                                                                                                                                                                                                                                                                                                                               "+
"	<AttrName>套餐参数</AttrName>                                                                                                                                                                                                                                                                                                                                              "+
"    <AttrValue></AttrValue>                                                                                                                                                                                                                                                                                                                                                 "+
"	<AttrValueName></AttrValueName>                                                                                                                                                                                                                                                                                                                                            "+
"	<DispSeq>0</DispSeq>                                                                                                                                                                                                                                                                                                                                                       "+
"</DetailOrderInfo>                                                                                                                                                                                                                                                                                                                                                          "+
"                                                                                                                                                                                                                                                                                                                                                                            "+
"<DetailOrderInfo>                                                                                                                                                                                                                                                                                                                                                           "+
"	<AttrID>30197838</AttrID>                                                                                                                                                                                                                                                                                                                                                  "+
"	<ProName>currentComboDesc</ProName>                                                                                                                                                                                                                                                                                                                                        "+
"	<AttrName>要办理的加餐包描述</AttrName>                                                                                                                                                                                                                                                                                                                                    "+
"    <AttrValue>5元包30M</AttrValue>                                                                                                                                                                                                                                                                                                                                         "+
"	<AttrValueName>5元包30M</AttrValueName>                                                                                                                                                                                                                                                                                                                                    "+
"	<DispSeq>0</DispSeq>                                                                                                                                                                                                                                                                                                                                                       "+
"</DetailOrderInfo>                                                                                                                                                                                                                                                                                                                                                          "+
"                                                                                                                                                                                                                                                                                                                                                                            "+
"<DetailOrderInfo>                                                                                                                                                                                                                                                                                                                                                           "+
"	<AttrID>30197837</AttrID>                                                                                                                                                                                                                                                                                                                                                  "+
"	<ProName>currentCombo</ProName>                                                                                                                                                                                                                                                                                                                                            "+
"	<AttrName>要办理的加餐包</AttrName>                                                                                                                                                                                                                                                                                                                                        "+
"    <AttrValue>001#YD0203-366#5004081#5734524#5#30</AttrValue>                                                                                                                                                                                                                                                                                                              "+
"	<AttrValueName>001#YD0203-366#5004081#5734524#5#30</AttrValueName>                                                                                                                                                                                                                                                                                                         "+
"	<DispSeq>0</DispSeq>                                                                                                                                                                                                                                                                                                                                                       "+
"</DetailOrderInfo>                                                                                                                                                                                                                                                                                                                                                          "+
"                                                                                                                                                                                                                                                                                                                                                                            "+
"</RequestBody>                                                                                                                                                                                                                                                                                                                                                              "+
"</ContractRoot>                                                                                                                                                                                                                                                                                                                                                             ";
		String xml = new String(reqXml.getBytes(), "UTF-8");
		 System.out.println(xml);
		 System.out.println( pt.getDocument(xml).asXML());

	}

}
